function clock() {
    var hours = document.getElementById('hour');
    var minutes = document.getElementById('minutes');
    var seconds = document.getElementById('seconds');
    var ampm = document.getElementById('ampm');

    var h = new Date().getHours();
    var m = new Date().getMinutes();
    var s = new Date().getSeconds();
    var am = "AM";
    
    if( h > 12){
        h = h - 12;
        var am = "PM";
    }

    h = (h < 10) ? "0" + h : h;
    m = (m < 10) ? "0" + m : m;
    s = (s < 10) ? "0" + s : s;

    hours.innerHTML = h;
    minutes.innerHTML = m;
    seconds.innerHTML = s;
    ampm.innerHTML = am;
    
}

var interval = setInterval(clock, 1000);

// This file is generated by Blackbox ai when i have error in my code so use this and upper code is mine. and i am shocked by this code which is given by Blackbox 🤯👌✅⬇️

// function clock() {
//     var hours = document.getElementById('hour');
//     var minutes = document.getElementById('minutes');
//     var seconds = document.getElementById('seconds');
//     var ampm = document.getElementById('ampm');

//     if (!hours || !minutes || !seconds || !ampm) {
//         console.error("One or more clock elements are missing.");
//         return;
//     }

//     var now = new Date();
//     var h = now.getHours();
//     var m = now.getMinutes();
//     var s = now.getSeconds();
//     var am = h < 12 ? "AM" : "PM";

//     h = h % 12; // convert to 12-hour format
//     h = (h < 10) ? "0" + h : h;
//     m = (m < 10) ? "0" + m : m;
//     s = (s < 10) ? "0" + s : s;

//     hours.innerHTML = h;
//     minutes.innerHTML = m;
//     seconds.innerHTML = s;
//     ampm.innerHTML = am;
// }

// setInterval(clock, 1000);